# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.provider "hyperv" do |h|
    h.vmname = "dev"
    h.maxmemory = 2048
    h.vm_integration_services = {
      guest_service_interface: true,
      CustomVMSRV: true
    }
  end
end